on: [push]

name: CI

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup protoc
        uses: arduino/setup-protoc@v2.1.0
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: cargo test
